- name: "Download Nodejs source"
  become: true
  #Updating Nodejs version from 13.x to 14.x, because 13.x is deprecated and make Ansible fails with CircleCi 
  shell: |
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - 

- name: "Install Nodejs"
  become: true
  apt: 
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install PM2"
  npm:
    name: pm2
    global: yes

