- name: "Create Backend Folder"
  file: 
    path: ~/backend
    state: directory

- name: "Decompress Backend Files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: "Installing NPM Dependencies"
  shell: |
    cd ~/backend
    npm install
 
- name: "Run Backend With PM2"
  shell: |
    cd ~/backend/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: print debug message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start automaticlly"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu